import type { DataDogSet, DoraSet, OutcomeSet, RadarSet, ReliabilitySet } from '../domain/sensors';

// --- The MCP / external-data seam ---------------------------------------------------
// The cockpit is a static client-side app, so real data arrives as a deploy-time SNAPSHOT
// (public/cockpit-data.json), generated by scripts/build-data.mjs from MCP/API connectors
// — the same pattern as build-info.json. Every field is OPTIONAL: a missing field means
// "use the synthetic default", so a partial snapshot degrades gracefully and an absent
// file (the default today) changes nothing.
//
// Instrument → real source (wire these in build-data.mjs when a connector exists):
//   outcomes    ← product analytics      (Amplitude / Mixpanel / PostHog)
//   reliability ← observability+incidents (Datadog / PagerDuty / Grafana)
//   dora        ← CI/CD + observability
//   datadog     ← production telemetry    (Datadog)
//   radar       ← issue tracker           (Jira / Linear / GitHub Projects)
export interface CockpitSnapshot {
  generatedAt: string; // ISO — when the snapshot was produced
  source: string; // e.g. 'synthetic' | 'mcp:datadog+jira+amplitude'
  signals?: {
    outcomes?: OutcomeSet;
    reliability?: ReliabilitySet;
    dora?: DoraSet;
    datadog?: DataDogSet;
    radar?: RadarSet;
  };
}

// The single seam every signal flows through once a connector is wired: prefer the real
// value, fall back to the synthetic default. Only `undefined` falls back — a real `0` or
// empty value is honoured.
export function resolveSignal<T>(fallback: T, override: T | undefined): T {
  return override ?? fallback;
}

// Fetch the deploy-time snapshot if present (served alongside the app, like build-info.json).
// Returns null when absent — the cockpit then keeps its synthetic data.
export async function loadSnapshot(): Promise<CockpitSnapshot | null> {
  try {
    const r = await fetch('/cockpit-data.json', { cache: 'no-store' });
    return r.ok ? ((await r.json()) as CockpitSnapshot) : null;
  } catch {
    return null;
  }
}
